{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "microservice-chart.fullname" . }}
  labels:
    {{- include "microservice-chart.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "microservice-chart.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        {{- with .Values.networkPolicy.ingressNamespaceSelector }}
        - namespaceSelector:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.networkPolicy.ingressPodSelector }}
        - podSelector:
            {{- toYaml . | nindent 12 }}
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
{{- end }}
