node.id=3
process.roles=broker,controller
listeners=PLAINTEXT://0.0.0.0:39092,CONTROLLER://0.0.0.0:39093
advertised.listeners=PLAINTEXT://localhost:39092
listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
controller.listener.names=CONTROLLER
inter.broker.listener.name=PLAINTEXT
controller.quorum.voters=1@kafka-1:19093,2@kafka-2:29093,3@kafka-3:39093
offsets.topic.replication.factor=3
transaction.state.log.replication.factor=3
transaction.state.log.min.isr=2
default.replication.factor=3
min.insync.replicas=2
num.partitions=4
log.retention.hours=24
log.segment.bytes=1073741824
auto.create.topics.enable=true
group.initial.rebalance.delay.ms=0
