-- Solutions 21 — Backup and PITR
SET search_path = sql_core, public;

-- Q1 — backup / archive GUCs
SELECT name, setting, unit, short_desc
  FROM pg_settings
 WHERE category ILIKE '%wal%archive%'
    OR name IN ('archive_mode','archive_command','archive_timeout',
                'wal_level','max_wal_senders','wal_compression')
 ORDER BY name;

-- Q2 — capture WAL delta around 100 inserts
SELECT pg_current_wal_lsn() AS lsn_before;
DROP TABLE IF EXISTS pit_ex21;
CREATE TABLE pit_ex21 (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, label text);
INSERT INTO pit_ex21 (label)
SELECT 'row-' || g FROM generate_series(1, 100) g;
SELECT pg_current_wal_lsn() AS lsn_after;
-- Bytes of WAL generated by the inserts:
SELECT pg_wal_lsn_diff(
         (SELECT pg_current_wal_lsn()),
         '0/0')::bigint
       AS cumulative_wal_bytes_since_cluster_start;

-- Q3 — force a CHECKPOINT, then read pg_stat_archiver
CHECKPOINT;
SELECT archived_count,
       last_archived_wal,
       last_archived_time,
       failed_count,
       last_failed_wal,
       last_failed_time
  FROM pg_stat_archiver;

-- Q4 — describe a test archive_command (do not actually run it)
-- ALTER SYSTEM SET archive_command = 'test ! -f /tmp/pg_archive_test/%f && cp %p /tmp/pg_archive_test/%f';
-- SELECT pg_reload_conf();
-- After the test: ALTER SYSTEM RESET archive_command; SELECT pg_reload_conf();
COMMENT ON SCHEMA public IS 'archive_command describes where WAL files are copied; see docs/06-tuning-cheatsheet.md';

-- Q5 — pg_stat_progress_basebackup during an in-progress backup
-- The view is empty unless pg_basebackup is running. To trigger:
--   docker compose -f docker/docker-compose.yml exec primary \
--     pg_basebackup -D /tmp/backup -Ft -z -P -U postgres
-- Then in psql:
SELECT pid, phase, backup_total, backup_streamed,
       tablespaces_total, tablespaces_streamed
  FROM pg_stat_progress_basebackup;

-- Q6 — recovery GUCs (read-only; only used when recovery.signal exists)
SHOW restore_command;
SHOW recovery_target_action;
SHOW recovery_target_inclusive;
SHOW recovery_target_time;
SHOW recovery_target_lsn;
SHOW recovery_target_xid;
SHOW recovery_target_name;

-- Q7 — PITR workflow (text answer):
-- 1. Take a base backup on the running primary:
--      pg_basebackup -h primary -D /backup/base_X -Ft -z -U postgres
-- 2. Enable WAL archiving on the primary:
--      ALTER SYSTEM SET archive_mode = on;
--      ALTER SYSTEM SET archive_command = 'cp %p /archive/%f';
--      SELECT pg_reload_conf();
-- 3. Verify archive is healthy:
--      SELECT * FROM pg_stat_archiver;
-- 4. To recover to a target time '2025-12-01 12:00:00 UTC':
--      a. Stop the primary.
--      b. Restore the base backup into a fresh PGDATA:
--           pg_basebackup ... extracted via tar -xf
--      c. Create /PGDATA/recovery.signal (empty file).
--      d. Add to postgresql.conf:
--           restore_command = 'cp /archive/%f %p'
--           recovery_target_time = '2025-12-01 12:00:00+00'
--           recovery_target_action = 'promote'
--      e. Start the recovered cluster: pg_ctl -D /PGDATA start
--      f. It replays WAL up to the target timestamp, then promotes.
-- 5. Verify: SELECT pg_is_in_recovery(); -- should be 'f'
