# rustfmt config
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
use_small_heuristics = "Default"
format_code_in_doc_comments = true
normalize_comments = false
normalize_doc_attributes = false
condense_wildcard_suffixes = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
